#

PLUGIN=		captcha

FILES=		autoinstall.php configuration_validation.php functions.inc install_defaults.php LICENSE 
DIRS=		language sql templates

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
