#

PLUGIN=		forum

FILES=		autoinstall.php config.php configuration_validation.php \
		functions.inc install_defaults.php upgrade.inc
DIRS=		docs include language sql

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
