#

PLUGIN=		calendarjp

FILES=		autoinstall.php functions.inc install_defaults.php \
		install_updates.php configuration_validation.php \
		readme_jp.html
DIRS=		include language sql templates

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
