#

PLUGIN=		filemgmt

FILES=		autoinstall.php config.php functions.inc history \
		install_defaults.php readme.htm update_20090602.html
MAKEPUBDIRS=	filemgmt_data/category_snaps filemgmt_data/files/tmp \
		filemgmt_data/snaps/tmp
PUBDIRMODE=	0775

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
