#

PLUGIN=		mycaljp

FILES=		README_JP autoinstall.php functions.inc history \
		install_defaults.php configuration_validation.php
DIRS=		language slidecalender

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
