#

PLUGIN=		dataproxy

FILES=		INSTALL INSTALL_ja autoinstall.php config.php dataproxy.php \
		functions.inc
DIRS=		drivers language templates

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
