#

PLUGIN=		autotags

FILES=		Changelog INSTALL INSTALL_ja.txt README_ja.txt TODO \
		autoinstall.php config.php configuration_validation.php \
		functions.inc install_defaults.php install_updates.php

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
