<?php

function CUSTOM_handle404($alternate_url = '')
{
     global $_CONF, $_USER, $LANG_404;

     // send 404 in any case
     header('HTTP/1.1 404 Not Found');
     header('Status: 404 Not Found');

    if (isset($_SERVER['SCRIPT_URI'])) {
        $url = $_SERVER['SCRIPT_URI'];
    } else {
        if (empty($_SERVER['HTTPS']) || ($_SERVER['HTTPS'] === 'off')) {
            $url = 'http';
        } else {
            $url = 'https';
        }

        $url .= '://' . @$_SERVER['HTTP_HOST'] . strip_tags($_SERVER['SCRIPT_URI']);
    }

    // Add log stuff
    if (empty($_USER['uid'])) {
        $byUser = 'anon@' . $_SERVER['REMOTE_ADDR'];
    } else {
        $byUser = $_USER['uid'] . '@' . $_SERVER['REMOTE_ADDR'];
    }

    $logEntry = "404 Error generated by {$byUser} for URL: {$url}";

    // Add referer
    if (!empty($_SERVER['HTTP_REFERER'])) {
        $logEntry .= " - Referring URL: {$_SERVER['HTTP_REFERER']}";
    }

    // Add user agent
    if (isset($_SERVER['HTTP_USER_AGENT'])) {
        $logEntry .= ' - User agent: ' . $_SERVER['HTTP_USER_AGENT'];
    }

    // Write into log file
    $logEntry = str_replace(array('<?', '?>'), array('(@', '@)'), $logEntry);
    $logEntry = @strftime('%c') . ' - ' . $logEntry . PHP_EOL;
    @file_put_contents($_CONF['path_log'] . '404.log', $logEntry, FILE_APPEND | LOCK_EX);

    $display = COM_startBlock($LANG_404[1]);
    
    if (is_callable('CUSTOM_getStaticpage')) {
        $display .= CUSTOM_getStaticpage('404');
    }
    
    $display .= COM_endBlock();
    $display = COM_createHTMLDocument(
        $display,
        array(
            'what' => 'none',
            'pagetitle' => $LANG_404[1], 
            'rightblock' => false
        )
    );
    COM_output($display);
    exit; // Do not want to go any further
}
