#

PLUGIN=		custommenu

FILES=		README_JP functions.inc install_defaults.php \
		readme_jp.html autoinstall.php install_updates.php \
		configuration_validation.php
DIRS=		bonus language sql

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
